### ISSUE TITLE
Record file path

### ISSUE THREAD

**Issue by ericjames** [gurmukhp/gulp-svg-json-spritesheet#6]
Is it possible to have the filenames reflect their path? I want to be able to have a fallback in case the SVG does not exist.

My svg is located in: `svg/sports/ball.svg`

becomes
```
	"/sports/ball.svg": {
		"data": "<svg..."
```

Therefore I can do a fallback to grab `https://mydomain.com/sports/ball.svg`

**Comment by gurmukhp** [comment]
[Fixed](https://github.com/gurmukhp/gulp-svg-json-spritesheet/commit/30e6eb6387bde34a8eb3beb82e1497f468c114f3)

**Comment by ericjames** [comment]
Sorry! I jumped the gun a little I was hoping I could specify the filepath:

```js
gulp.task('build:svgs', function() {
    var svg = require('gulp-svg-json-spritesheet');
    return gulp.src('webroot/svg/*.svg') // My root directory ./webroot/
        .pipe(svg({
            fileName: 'sprites.json',
            svgPath: '/svg/' // because .htaccess points to https://mydomain.com/svg/**.svg 
        }))
        .pipe(gulp.dest('webroot/scripts')); // Store file in javascript root
});
```

Becomes
```json
{
	"/svg/ball.svg": {
		"data": "<svg..."
       }
}
```

**Comment by gurmukhp** [comment]
Got it, the latest changes should be what you're after. Let me know if it works :-)
